spring.application.name=shipment-api-service

# --- Database Configuration (for LAB 1) ---
# Connects to the 'training-database' container (exposed on localhost:5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/trainingdb
spring.datasource.username=user
spring.datasource.password=password

# --- JPA (Hibernate) Configuration ---
# 'update': Allows Hibernate to automatically create/update tables
# based on your @Entity classes (very useful during development)
spring.jpa.hibernate.ddl-auto=update